### PR TITLE
feat(client): l1<>l2 messaging crate

### LINKED ISSUE #204: feat(l1): Implement l1<>l2 messaging
### Is there an existing issue?

- [X] I have searched the existing issues

### Motivation

We need to implement the reading of messages from L1 in Madara. For more context about L1-L2 messaging, I recommend visiting this [link](https://docs.starknet.io/architecture-and-concepts/network-architecture/messaging-mechanism/). This implementation is relatively straightforward and does not require significant changes, as it complements the L2 state verification mechanism via L1 already implemented in Deoxys. The principle is simple: for L1 verification, we continuously subscribe to the `logStateUpdate` event from the core contract to receive the latest verified block number, block hash, and state root. The L1 messaging works similarly by subscribing to the `logMessageToL2` event and aggregating the received data into an L1 handler transaction format to the transaction pool.

### Request

This implementation involves a slight refactor of how we initialize an Ethereum client in Deoxys. Currently, it is a simple module `l1.rs` in `client/sync` [link](https://github.com/KasarLabs/deoxys/blob/main/crates/client/sync/src/l1.rs). We would like to have a dedicated `l1` crate in `client/` [link](https://github.com/KasarLabs/deoxys/blob/main/crates/client/) to facilitate its multiple uses across the codebase. This crate will also be used to retrieve the L1 gas price. The L1<>L2 messaging implementation is already in Madara. The initial objective is to set up a proper L1 client on the client side and then implement the necessary modules (L1<>L2 messaging, gas price, `logStateUpdate`).

### Solution

1. **Set Up a Proper L1 Client:**
   - Create a dedicated `l1` crate in the `client/` directory.
   - Ensure this crate can be easily dispatched for multiple uses across the codebase.

2. **Implement Necessary Modules:**
   - L1<>L2 messaging module: Subscribe to the `logMessageToL2` event and aggregate data into the L1 handler transaction format.
   - Gas price module: Retrieve the L1 gas price (dedicated pr will be linked here).
   - `logStateUpdate` module: Subscribe to the `logStateUpdate` event to continuously receive the latest verified `block number`, `block hash`, and `state root`.

### Are you willing to help with this request?

Yes!

### PR DESCRIPTION
**Pull request by azurwastaken**
# Pull Request type

- Feature

## What is the current behavior?

Resolves: #204

## What is the new behavior?

- Added a crate with a worker that listen for LogMessageToL2 event on main contract and handle it as the old madara did.
- Added some entries to the db for messaging related data

## Does this introduce a breaking change?

No 

## Usefull information

🚨Require #208 🚨
This PR include a lot of code from #208 as we started from it to build with the feature from the eth crate.

A few notes on the current design:
- There is no guarantee that L1->L2 messages will be executed in a centralized context.
- There is no ordering guarantee, nonces are solely used 

### Overall Workflow
- [X] Create a stream of LogMessageToL2 events
- [X] Get last synced block from Messaging DB
- [X] Consume the stream and log event
- [ ] Process message 
    - [X] Parse tx fee
    - [X] Parse transaction from event
    - [X] Check if message has already been processed
    - [X] Build transaction
    - [Waiting for mempool #198 ] Submit tx to mempool
    - [X] Update Messaging DB
    
### Specific case to handle    
- [ ] Handle Message Cancellation (https://github.com/keep-starknet-strange/madara/issues/1638)

### Tests

- [ ] E2E test 1
    - Launch Anvil Node
    - Launch Worker
    - Send L1->L2 message
    - Assert that event is emitted on L1
    - Assert that even was caught by the worker with correct data
    - Assert the tx hash computed by the worker is correct
    - Assert that the tx has been included in the mempool
    - Assert that DB was correctly updated (last synced block & nonce)
    - Assert that the tx was correctly executed

- [ ]  E2E test 2
    - Should fail if we try to send multiple messages with same nonces

- [ ]  E2E test 3 
    - Message Cancellation

### CODE REVIEW

**Comment by Mohiiit** [comment]
Hey @azurwastaken, we were thinking of a different approach about the structure of the code. So instead of creating l1-messaging a different crate, we can have it inside the eth-crate, just like update_state. And as of now we are joining l1_sync with l1_messages_sync and l2_sync, so I was thinking to join l1_sync and l2_sync and inside the l1_sync we will have l1_messages_sync, state_update_sync and l1_gas_price sync, wdyt?

so structure of the code we had in mind was:

- eth-crate
    |_____ state_update
    |_____ l1_messages
    |_____ l1_gas_price
    |_____ maybe a `sync.rs` with sync function which calls above 3
    
and the above `sync` function get called in the `sync` crate, inside the `starknet_sync_worker`, wdyt?

cc: @cchudant

**Comment by azurwastaken** [comment]
> Hey @azurwastaken, we were thinking of a different approach about the structure of the code. So instead of creating l1-messaging a different crate, we can have it inside the eth-crate, just like update_state. And as of now we are joining l1_sync with l1_messages_sync and l2_sync, so I was thinking to join l1_sync and l2_sync and inside the l1_sync we will have l1_messages_sync, state_update_sync and l1_gas_price sync, wdyt?
> 
> so structure of the code we had in mind was:
> 
> * eth-crate
>   |_____ state_update
>   |_____ l1_messages
>   |_____ l1_gas_price
>   |_____ maybe a `sync.rs` with sync function which calls above 3
> 
> and the above `sync` function get called in the `sync` crate, inside the `starknet_sync_worker`, wdyt?
> 
> cc: @cchudant

Hey @Mohiiit , yes you are right, its porbably better if everything is together

**Comment by cchudant** [comment]
> Hey @azurwastaken, we were thinking of a different approach about the structure of the code. So instead of creating l1-messaging a different crate, we can have it inside the eth-crate, just like update_state. And as of now we are joining l1_sync with l1_messages_sync and l2_sync, so I was thinking to join l1_sync and l2_sync and inside the l1_sync we will have l1_messages_sync, state_update_sync and l1_gas_price sync, wdyt?
> 
> so structure of the code we had in mind was:
> 
>     * eth-crate
>       |_____ state_update
>       |_____ l1_messages
>       |_____ l1_gas_price
>       |_____ maybe a `sync.rs` with sync function which calls above 3
> 
> 
> and the above `sync` function get called in the `sync` crate, inside the `starknet_sync_worker`, wdyt?
> 
> cc: @cchudant

yes that makes sense
however a small thing here: i dont want the eth crate to be called from sync, i'd like it to be a Service so that i can just activate it even when doing block production (not sync) mode

also in the future this eth crate will expose a common interface to the rest of the app that is swappable with other chains (e.g for starknet L3s) but i'm getting ahead of myself

**Comment by azurwastaken** [comment]
Outdated, see #220

**Pull request closed without merging**
