### PR TITLE
fix: FeePayment conversion

### LINKED ISSUE #385: fix(fgw): adapt FeePayment conversion for ConfirmedReceipt (gateway) based on tx version
### Is there an existing issue?

- [X] I have searched the existing issues

### Description of bug

Currently, the conversion of Felt to FeePayment defaults the PriceUnit to Wei:
```rust
impl From<Felt> for FeePayment {
    fn from(fee: Felt) -> Self {
        Self { amount: fee, unit: PriceUnit::Wei }
    }
}
```

however, the correct PriceUnit (either Wei or Fri) depends on the TransactionVersion, which is not directly accessible in the receipt structure. This leads to potential mismatches in fee representation for gateway receipts

the FeePayment conversion should dynamically determine the correct PriceUnit based on the tx version associated with the transaction that produced the receipt

### Steps to reproduce

_No response_

### PR DESCRIPTION
**Pull request by jbcaron**
## Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Bugfix

## What is the current behavior?

Resolves: #385 

## What is the new behavior?

- the UnitPrice for FeePayment depends on the transaction version
-

## Does this introduce a breaking change?

data for FeePayment in older databases is incorrect for transaction V3

### CODE REVIEW

**Comment by Mohiiit** [comment]
hello ser, can you share some docs/spec to read from about this?

**Comment by jbcaron** [comment]
> hello ser, can you share some docs/spec to read from about this?

there aren’t really any specs for the sequencer types

**Review by Mohiiit — APPROVED** [review]

**Review by Trantorian1 — APPROVED** [review]
Seems good :+1:

**Comment by jbcaron** [comment]
https://docs.starknet.io/architecture-and-concepts/network-architecture/transactions/
In this document, only the V3 transactions have their fees expressed in Fri.

**Pull request merged**
